# CI/CD image for the TBBRDet Model
#
# To build the image:
# $ docker build -t <dockerhub_user>/<dockerhub_repo> --build-arg arg=value .
# or using default args:
# $ docker build -t <dockerhub_user>/<dockerhub_repo> .
#
# [!] Note: For the Jenkins CI/CD pipeline, input args are defined inside the
# Jenkinsfile, not here!

# Base image
FROM deephdc/uc-emvollmer-deep-oc-tbbrdet_api:base

LABEL maintainer='Elena Vollmer'
LABEL version='0.0.1'
# CI/CD image for the TBBRDet Model

# Install Ubuntu packages
RUN apt-get update && \
# Clean up
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

# Set LANG environment
ENV LANG C.UTF-8

# install python tools necessary for code testing
RUN pip3 install --no-cache-dir tox==2.9.0 flake8 pylint pydocstyle pep8 'bandit>=1.1.0' sphinx \
    coverage==6.2 pytest pytest-cov 'stestr>=1.0.0' 'testtools>=1.4.0'
# otherwise issues with twine<=1.10.0
RUN pip3 install --no-cache-dir twine==1.11.0
RUN pip3 install --no-cache-dir -U wheel setuptools

# Install rclone (need to communicate with remote storages)
RUN curl -O https://downloads.rclone.org/rclone-current-linux-amd64.deb && \
    dpkg -i rclone-current-linux-amd64.deb && \
    apt install -f && \
    mkdir /srv/.rclone/ && \
    touch /srv/.rclone/rclone.conf && \
    rm rclone-current-linux-amd64.deb && \
    rm -rf /var/lib/apt/lists/*

ENV RCLONE_CONFIG=/srv/.rclone/rclone.conf

# Set the working directory
WORKDIR /srv

# Set environment
ENV PBR_VERSION=0.0.1

# Install TBBRDet and tbbrdet_api in editable mode
# RUN git clone --depth 1 -b master --recurse-submodules https://github.com/emvollmer/tbbrdet_api.git && \
#    cd tbbrdet_api && \
#    git pull --recurse-submodules && \
#    git submodule update --remote --recursive && \
#    # those packages below should be in requirements.txt
#    pip3 install --no-cache-dir \
#        future \
#        tensorboard \
#        mlflow \
#        joblib \
#        tqdm && \
#    pip3 install --no-cache-dir -e ./TBBRDet && \
#    pip3 install --no-cache-dir -e .

CMD ["tail","-f","/dev/null"]
